#!/bin/sh -e
set -x
PUID=${PUID:-911}
PGID=${PGID:-911}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc
whoami
chown -R abc:abc /opt
su - abc -s /bin/sh -c  "/opt/conda/envs/obb/bin/jupyter lab /config/.jupyter/jupyter_lab_config.py"
sex +x
