#!/bin/sh -e
set -x
PUID=${PUID:-911}
PGID=${PGID:-911}
sudo groupmod -o -g "$PGID" abc
sudo usermod -o -u "$PUID" abc
whoami
sudo chown -R abc:abc /opt

if grep -q "/opt/conda/etc/profile.d/conda.sh"  /config/.bashrc; then
    echo "Found!"
else
echo ". /opt/conda/etc/profile.d/conda.sh" >>  /config/.bashrc
fi

if grep -q "conda activate openbb"  /config/.bashrc; then
    echo "Found!"
else
echo "conda activate openbb" >> /config/.bashrc
fi

if [ -z "$CONFIG_FILE" ]; then
#     su - abc -s /bin/sh -c "/opt/conda/envs/openbb/bin/jupyter lab --config=/config/.jupyter/jupyter_lab_config.py"
     /opt/conda/envs/openbb/bin/jupyter lab --config=/config/.jupyter/jupyter_lab_config.py
else
    # 如果非空，使用环境变量的值
     /opt/conda/envs/openbb/bin/jupyter lab --config=$CONFIG_FILE
fi


sex +x
